services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    environment:
        # https://octoeverywhere.com/s/access-code
      - ACCESS_CODE
        # https://octoeverywhere.com/s/bambu-sn
      - SERIAL_NUMBER
        # Find using the printer's display
      - PRINTER_IP
    volumes:
      # Specify a path mapping for the required persistent storage
      - /data:/data

  # Add as many printers as you want!
  # octoeverywhere-bambu-connect-2:
  #   image: octoeverywhere/octoeverywhere:latest
  #   environment:
  #       # https://octoeverywhere.com/s/access-code
  #     - ACCESS_CODE2
  #       # https://octoeverywhere.com/s/bambu-sn
  #     - SERIAL_NUMBER2
  #       # Find using the printer's display
  #     - PRINTER_IP2
  #   volumes:
  #     # Specify a path mapping for the required persistent storage
  #     - /data2:/data